menu:
- {name: 'home', url: '/'}
- {name: 'team', url: '/team'}
- {name: 'awards', url: '/awards'}
- {name: 'publications', url: '/publications'}
# - {name: 'teaching', url: '/teaching'}
# - {name: 'cv', url: '/cv'}
- {name: 'join&nbsp;us', url: '/joinus'}
# - {name: 'contact', url: '/contact'}
- {name: '中文', url: '/cn'}

honorarychairs:
- {name: 'Shengli LIU', title: 'Professor', department: 'Student Innovation Center', institution: 'Shanghai Jiao Tong University', image: 'assets/img/faculty/liushengli.png', url: ''}
- {name: 'Xiaokang YANG', title: 'Professor', department: 'Artificial Intelligence Institute, SEIEE', institution: 'Shanghai Jiao Tong University', image: 'assets/img/faculty/yangxiaokang.png', url: ''}


headofclass:
# - {name: 'Kevin ZHAO Weiming', title: 'Researcher', department: 'Student Innovation Center', institution: 'Shanghai Jiao Tong University', image: 'assets/img/faculty/zhaoweiming.png', url: 'primary-investigator'}
- {name: 'Pengzhi CHU', title: 'Researcher', department: 'Student Innovation Center', institution: 'Shanghai Jiao Tong University', image: 'assets/img/faculty/chupengzhi.png', url: 'https://www.si.sjtu.edu.cn/content/person-detail?params=69203cf7b7cf4f88bb55c94bd1f47646&menuIds=2,7,12'}
- {name: 'Yichao YAN', title: 'Assistant Professor', department: 'Artificial Intelligence Institute, SEIEE', institution: 'Shanghai Jiao Tong University', image: 'assets/img/faculty/yanyichao.png', url: 'https://daodaofr.github.io'}
- {name: 'Kevin&nbsp;ZHAO&nbsp;Weiming', title: 'Researcher', department: 'Student Innovation Center', institution: 'Shanghai Jiao Tong University', image: 'assets/img/faculty/zhaoweiming.png', url: 'https://zwm0426.github.io'}

classof2024:
- {name: 'Juntao CHENG', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2024/chengjuntao.png', url: ''}
- {name: 'Dayong FANG', school: 'University of Michigan – Shanghai Jiao Tong University Joint Institute', image: 'assets/img/classof2024/fangdayong.png', url: ''}
- {name: 'Yiheng GE', school: 'School of Mechanical Engineering', image: 'assets/img/classof2024/geyiheng.png', url: ''}
- {name: 'Jiayi JI', school: 'Antai College of Economics and Management', image: 'assets/img/classof2024/jijiayi.png', url: ''}
- {name: 'Yige JU', school: 'School of Design', image: 'assets/img/classof2024/juyige.png', url: ''}
- {name: 'Hanqi LI', school: 'School of Design', image: 'assets/img/classof2024/lihanqi.png', url: ''}
- {name: 'LiXin LU', school: 'School of Mechanical Engineering', image: 'assets/img/classof2024/lulixin.png', url: ''}
- {name: 'Yi LU', school: 'Global Institue of Future Technology', image: 'assets/img/classof2024/luyi.png', url: ''}
- {name: 'Yibo LUO', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2024/luoyibo.png', url: ''}
- {name: 'Qinyuan MIAO', school: 'Ecole d''Ingénieurs Paris at SJTU', image: 'assets/img/classof2024/miaqinyuan.png', url: ''}
- {name: 'Jincheng NIE', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2024/niejincheng.png', url: ''}
- {name: 'Tian QI', school: 'School of Mathematical Sciences', image: 'assets/img/classof2024/qitian.png', url: ''}
- {name: 'Yining QIAO', school: 'Antai College of Economics and Management', image: 'assets/img/classof2024/qiaoyining.png', url: ''}
- {name: 'Zhida SONG', school: 'School of Medicine', image: 'assets/img/classof2024/songzhida.png', url: ''}
- {name: 'Zhaoyuan WAN', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2024/wanzhaoyuan.png', url: ''}
- {name: 'Tao WANG', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2024/wangtao.png', url: ''}
- {name: 'Zeming WANG', school: 'School of Physics and Astronomy', image: 'assets/img/classof2024/wangzeming.png', url: ''}
- {name: 'Zenan WU', school: 'Antai College of Economics and Management', image: 'assets/img/classof2024/wuzezan.png', url: ''}
- {name: 'Yifan YUAN', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2024/yuanyifan.png', url: ''}
- {name: 'Lin ZHANG', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2024/zhanglin.png', url: ''}
- {name: 'Tianao ZHANG', school: 'School of Ocean and Civil Engineering', image: 'assets/img/classof2024/zhangtianao.png', url: ''}
- {name: 'Zijin ZHOU', school: 'Global Institue of Future Technology', image: 'assets/img/classof2024/zhouzijin.png', url: ''}
- {name: 'Rui ZHU', school: 'Antai College of Economics and Management', image: 'assets/img/classof2024/zhurui.png', url: ''}


classof2023: 
# - {name: 'Kangjie BAO', school: 'School of Mathematical Sciences', image: 'assets/img/classof2023/baokangjie.png', url: ''}
# - {name: 'Zicong CHENG', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/chengzicong.png', url: ''}
- {name: 'Kangjie BAO', school: 'School of Mathematical Sciences', image: 'assets/img/classof2023/baokangjie.png', url: ''}
- {name: 'Zicong CHENG', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/chengzicong.png', url: ''}
- {name: 'Shan GAO', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/gaoshan.png', url: ''}
- {name: 'Rui GE', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/gerui.png', url: ''}
- {name: 'Yuhan GUO', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/guoyuhan.png', url: ''}
- {name: 'Junxiao KONG', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/kongjunxiao.png', url: ''}
- {name: 'Dongxiao LI', school: 'Ecole d''Ingénieurs Paris at SJTU', image: 'assets/img/classof2023/lidongxiao.png', url: ''}
- {name: 'Jize LIU', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/liujize.png', url: ''}
- {name: 'Yitian LIU', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/liuyitian.png', url: ''}
- {name: 'Jiacheng LU', school: 'Antai College of Economics and Management', image: 'assets/img/classof2023/lujiacheng.png', url: ''}
- {name: 'Zerui PENG', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/pengzerui.png', url: ''}
- {name: 'Bolin QIU', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/qiubolin.png', url: ''}
- {name: 'Yikang RUAN', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/ruanyikang.png', url: ''}
- {name: 'Zhe SHUAI', school: 'School of Design', image: 'assets/img/classof2023/shuaizhe.png', url: ''}
- {name: 'Xinwen TONG', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/tongxinwen.png', url: ''}
- {name: 'Yuhang WANG', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/wangyuhang.png', url: ''}
- {name: 'Xinyuan XIA', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/xiaxinyuan.png', url: ''}
- {name: 'Congsheng XU', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/xucongsheng.png', url: ''}
- {name: 'Heyi XU', school: 'School of Design', image: 'assets/img/classof2023/xuheyi.png', url: ''}
- {name: 'Guanju YAN', school: 'School of Physics and Astronomy', image: 'assets/img/classof2023/yanguanju.png', url: ''}
- {name: 'Yikun ZENG', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/zengyikun.png', url: ''}
- {name: 'Jiashuo ZHANG', school: 'School of Mathematical Sciences', image: 'assets/img/classof2023/zhangjiashuo.png', url: ''}
- {name: 'Wenkang ZHANG', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/zhangwenkang.png', url: ''}
- {name: 'Yu ZHAO', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/zhaoyu.png', url: ''}
- {name: 'Yimao ZHOU', school: 'School of Humanities', image: 'assets/img/classof2023/zhouyimao.png', url: ''}


people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

# courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
# - {icon: 'github', link: 'https://github.com/LeNPaul'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Kevin ZHAO Weiming', title: 'Co-chair of AIGC Class', department: 'SJTU AIGC Class', institution: 'Shanghai Jiao Tong University', institution_address: '800 Dongchuan Road, Minhang, Shanghai, China', email: 'aigc#sjtu.edu.cn', office: 'Room B300, Student Innovation Center'}
